basePath: /
definitions:
  handlers.Credentials:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a GO API.
  title: Go API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Logs in a user with email and password, and returns a JWT token.
      parameters:
      - description: Email and Password
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/handlers.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Login to generate a JWT token
      tags:
      - Authentication
securityDefinitions:
  BearerAuth:
    description: Provide your token with prefix "Bearer "
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
